# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
image: wearepvtl/bitbucket-pipelines-git-ftp:latest

pipelines:
   default:
     - step:
        script:
            - git ftp push --force --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://fiestamexicangrill66.com
